input {
  file {
    path => [
#----------------CHANGE/UPDATE/REMOVE ACCORDING TO YOUR FILE NAMES-----------------#
      "/parser_output/apache_access_logs.json", 
      "/parser_output/mail_apache_access_logs.json",
      "/parser_output/mail_auth_logs.json",
      "/parser_output/mail_login_logs.json",
      "/parser_output/mail_smtp_logs.json",
      "/parser_output/postfix_logs.json",
      "/parser_output/waf-nginx-access_logs.json",
      "/parser_output/web_auth_logs.json"
    ]

    start_position => "end"          # 
    sincedb_path => "/usr/share/logstash/data/sincedb"  # 
    codec => json
    mode => "tail"
  }
}


filter {

  # Prefer meta.server (FLAT field)
  if [meta.server] {
    mutate {
      replace => {
        "[host][name]" => "%{[meta.server]}"
      }
    }
  }
  # Fallback to meta.source_host (FLAT field)
  else if [meta.source_host] {
    mutate {
      replace => {
        "[host][name]" => "%{[meta.source_host]}"
      }
    }
  }

  # Remove ECS event.original (safe)
  mutate {
    remove_field => [ "[event][original]" ]
  }
}


output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    cacert => "/usr/share/logstash/config/certs/ca.crt"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "all-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
